import type { TopicMap } from "./types";

const en: TopicMap = {
  "charades-for-kids": {
    meta: {
      title: "Charades for Kids - Easy Words, Rules & Family Game Ideas",
      description:
        "Kid-friendly charades rules, easy word ideas, and tips for family game night. Safe, fun, and simple to play at home or school.",
    },
    breadcrumb: "Charades for Kids",
    heading: "Charades for Kids: Fun, Safe & Easy to Learn",
    intro:
      "Charades is one of the best party games for children because it builds creativity, teamwork, and confidence. This guide covers kid-friendly rules, easy word ideas, and tips for parents and teachers.",
    sections: [
      {
        heading: "Why Kids Love Charades",
        paragraphs: [
          "Children enjoy acting, guessing, and laughing together. Charades keeps everyone moving and engaged without screens.",
          "It also helps younger players practice vocabulary, non-verbal communication, and turn-taking.",
        ],
      },
      {
        heading: "Kid-Friendly Rules",
        list: [
          "Use easy words: animals, jobs, everyday actions, and favorite characters.",
          "Allow extra time (90 seconds) for younger players.",
          "Let kids act in pairs if they feel shy.",
          "Skip difficult words without penalty.",
          "Keep scores light—focus on fun, not competition.",
        ],
      },
      {
        heading: "Easy Charades Words for Kids",
        list: [
          "Cat, dog, fish, butterfly, dinosaur",
          "Jump, sleep, eat, dance, read",
          "Teacher, doctor, superhero, pirate",
          "Pizza, ice cream, banana, cookie",
          "Birthday party, swimming, hide and seek",
        ],
      },
      {
        heading: "Tips for Parents & Teachers",
        list: [
          "Preview the word list before playing.",
          "Demonstrate one round so kids understand gestures.",
          "Celebrate creative acting, not just fast guesses.",
          "Rotate actors often so every child participates.",
        ],
      },
    ],
    cta: "Play Free Charades Online",
  },
  "charades-words": {
    meta: {
      title: "Charades Word List - 300+ Ideas by Category & Difficulty",
      description:
        "300+ charades words sorted by animals, food, movies, sports, jobs, verbs, and more. Easy, medium, and hard lists for parties, classrooms, and family game night.",
    },
    breadcrumb: "Charades Word List",
    heading: "Charades Word List: 300+ Ideas for Every Party",
    intro:
      "A great charades game starts with the right word list. Below are 300+ printable-style ideas across eleven categories, each split into easy, medium, and hard difficulty. Copy words onto slips, filter by category in our free online game, or mix rounds for family nights, classrooms, and team building.",
    sections: [
      {
        heading: "How to Use This List",
        paragraphs: [
          "Pick one category per round, or shuffle easy words for kids and hard words for adults. Actors get 45–90 seconds depending on age; no talking, no props, standard gestures only.",
          "For mixed-age groups, use mostly easy and medium words. Save hard phrases and obscure titles for adult-only rounds.",
        ],
        list: [
          "Easy: single nouns most people know (cat, pizza, doctor).",
          "Medium: longer titles, compound ideas, or less common vocabulary.",
          "Hard: abstract phrases, classic films, or words that need creative mime.",
        ],
      },
      {
        heading: "Animals (40 words)",
        wordGrids: [
          {
            label: "Easy (15)",
            words: [
              "Cat",
              "Dog",
              "Fish",
              "Bird",
              "Rabbit",
              "Horse",
              "Cow",
              "Pig",
              "Sheep",
              "Chicken",
              "Duck",
              "Frog",
              "Snake",
              "Butterfly",
              "Penguin",
            ],
          },
          {
            label: "Medium (15)",
            words: [
              "Elephant",
              "Giraffe",
              "Kangaroo",
              "Octopus",
              "Hedgehog",
              "Flamingo",
              "Crocodile",
              "Dolphin",
              "Owl",
              "Squirrel",
              "Peacock",
              "Turtle",
              "Shark",
              "Panda",
              "Koala",
            ],
          },
          {
            label: "Hard (10)",
            words: [
              "Chameleon",
              "Platypus",
              "Narwhal",
              "Armadillo",
              "Orangutan",
              "Jellyfish",
              "Porcupine",
              "Komodo dragon",
              "Sloth",
              "Mantis shrimp",
            ],
          },
        ],
      },
      {
        heading: "Food & Drink (35 words)",
        wordGrids: [
          {
            label: "Easy (15)",
            words: [
              "Pizza",
              "Apple",
              "Banana",
              "Ice cream",
              "Cookie",
              "Sandwich",
              "Pasta",
              "Rice",
              "Bread",
              "Cheese",
              "Egg",
              "Milk",
              "Juice",
              "Water",
              "Cake",
            ],
          },
          {
            label: "Medium (12)",
            words: [
              "Sushi",
              "Taco",
              "Burrito",
              "Pancake",
              "Waffle",
              "Popcorn",
              "Hot dog",
              "French fries",
              "Smoothie",
              "Chocolate",
              "Strawberry",
              "Watermelon",
            ],
          },
          {
            label: "Hard (8)",
            words: [
              "Croissant",
              "Guacamole",
              "Cappuccino",
              "Pad thai",
              "Fish and chips",
              "Birthday cake",
              "Pumpkin spice latte",
              "Chicken parmesan",
            ],
          },
        ],
      },
      {
        heading: "Movies & Characters (40 words)",
        wordGrids: [
          {
            label: "Easy (15)",
            words: [
              "Lion King",
              "Frozen",
              "Spiderman",
              "Toy Story",
              "Batman",
              "Superman",
              "Mickey Mouse",
              "Elsa",
              "Shrek",
              "Finding Nemo",
              "Moana",
              "Cinderella",
              "Pirates",
              "Star Wars",
              "Minions",
            ],
          },
          {
            label: "Medium (15)",
            words: [
              "Harry Potter",
              "Avengers",
              "Jurassic Park",
              "Inside Out",
              "The Incredibles",
              "Wicked",
              "Barbie",
              "Black Panther",
              "Wonder Woman",
              "Jaws",
              "Ghostbusters",
              "Back to the Future",
              "The Little Mermaid",
              "Encanto",
              "Zootopia",
            ],
          },
          {
            label: "Hard (10)",
            words: [
              "Inception",
              "The Godfather",
              "Casablanca",
              "Citizen Kane",
              "Pulp Fiction",
              "Schindler's List",
              "The Shawshank Redemption",
              "Blade Runner",
              "Parasite",
              "Everything Everywhere All at Once",
            ],
          },
        ],
      },
      {
        heading: "Sports & Activities (32 words)",
        wordGrids: [
          {
            label: "Easy (12)",
            words: [
              "Football",
              "Basketball",
              "Soccer",
              "Swimming",
              "Running",
              "Dancing",
              "Cycling",
              "Skating",
              "Yoga",
              "Hiking",
              "Jumping rope",
              "Bowling",
            ],
          },
          {
            label: "Medium (12)",
            words: [
              "Gymnastics",
              "Surfing",
              "Rock climbing",
              "Tennis",
              "Golf",
              "Volleyball",
              "Skiing",
              "Snowboarding",
              "Martial arts",
              "Archery",
              "Fencing",
              "Rowing",
            ],
          },
          {
            label: "Hard (8)",
            words: [
              "Equestrian",
              "Water polo",
              "Curling",
              "Pole vault",
              "Triathlon",
              "Synchronized swimming",
              "Luge",
              "Decathlon",
            ],
          },
        ],
      },
      {
        heading: "Jobs & Professions (30 words)",
        wordGrids: [
          {
            label: "Easy (12)",
            words: [
              "Teacher",
              "Doctor",
              "Nurse",
              "Chef",
              "Police officer",
              "Firefighter",
              "Farmer",
              "Artist",
              "Singer",
              "Dancer",
              "Pilot",
              "Driver",
            ],
          },
          {
            label: "Medium (10)",
            words: [
              "Engineer",
              "Scientist",
              "Lawyer",
              "Architect",
              "Journalist",
              "Veterinarian",
              "Mechanic",
              "Photographer",
              "Librarian",
              "Electrician",
            ],
          },
          {
            label: "Hard (8)",
            words: [
              "Astronaut",
              "Archaeologist",
              "Neurosurgeon",
              "Paleontologist",
              "Diplomat",
              "Sommelier",
              "Cartographer",
              "Forensic analyst",
            ],
          },
        ],
      },
      {
        heading: "Actions & Verbs (40 words)",
        wordGrids: [
          {
            label: "Easy (15)",
            words: [
              "Sleep",
              "Eat",
              "Drink",
              "Run",
              "Jump",
              "Dance",
              "Read",
              "Write",
              "Sing",
              "Laugh",
              "Cry",
              "Cook",
              "Clean",
              "Brush teeth",
              "Take a shower",
            ],
          },
          {
            label: "Medium (15)",
            words: [
              "Celebrate",
              "Apologize",
              "Propose",
              "Negotiate",
              "Meditate",
              "Stretch",
              "Whisper",
              "Shout",
              "Sneak",
              "Balance",
              "Juggle",
              "Knit",
              "Garden",
              "Bake",
              "Exercise",
            ],
          },
          {
            label: "Hard (10)",
            words: [
              "Procrastinate",
              "Brainstorm",
              "Negotiate peace",
              "File taxes",
              "Parallel park",
              "Change a tire",
              "Give a speech",
              "Conduct an orchestra",
              "Perform surgery",
              "Solve a puzzle",
            ],
          },
        ],
      },
      {
        heading: "Places & Travel (30 words)",
        wordGrids: [
          {
            label: "Easy (12)",
            words: [
              "School",
              "Home",
              "Park",
              "Beach",
              "Hospital",
              "Store",
              "Restaurant",
              "Library",
              "Airport",
              "Zoo",
              "Museum",
              "Farm",
            ],
          },
          {
            label: "Medium (10)",
            words: [
              "Mountains",
              "Desert",
              "Waterfall",
              "Castle",
              "Subway",
              "Campground",
              "Amusement park",
              "Skyscraper",
              "Lighthouse",
              "Train station",
            ],
          },
          {
            label: "Hard (8)",
            words: [
              "Eiffel Tower",
              "Great Wall of China",
              "Grand Canyon",
              "Santorini",
              "Machu Picchu",
              "Northern Lights",
              "Sahara Desert",
              "Times Square",
            ],
          },
        ],
      },
      {
        heading: "Objects & Everyday Items (35 words)",
        wordGrids: [
          {
            label: "Easy (15)",
            words: [
              "Phone",
              "Book",
              "Chair",
              "Table",
              "Lamp",
              "Umbrella",
              "Keys",
              "Wallet",
              "Backpack",
              "Glasses",
              "Watch",
              "Pen",
              "Pillow",
              "Blanket",
              "Toothbrush",
            ],
          },
          {
            label: "Medium (12)",
            words: [
              "Laptop",
              "Camera",
              "Headphones",
              "Microwave",
              "Vacuum cleaner",
              "Bicycle",
              "Skateboard",
              "Suitcase",
              "Telescope",
              "Hammer",
              "Scissors",
              "Alarm clock",
            ],
          },
          {
            label: "Hard (8)",
            words: [
              "Chandelier",
              "Sewing machine",
              "Record player",
              "Typewriter",
              "Compass",
              "Microscope",
              "Thermostat",
              "Fire extinguisher",
            ],
          },
        ],
      },
      {
        heading: "Nature & Weather (25 words)",
        wordGrids: [
          {
            label: "Easy (10)",
            words: [
              "Sun",
              "Rain",
              "Snow",
              "Wind",
              "Cloud",
              "Rainbow",
              "Tree",
              "Flower",
              "River",
              "Ocean",
            ],
          },
          {
            label: "Medium (8)",
            words: [
              "Thunderstorm",
              "Lightning",
              "Tornado",
              "Volcano",
              "Earthquake",
              "Avalanche",
              "Sunset",
              "Full moon",
            ],
          },
          {
            label: "Hard (7)",
            words: [
              "Hurricane",
              "Solar eclipse",
              "Northern Lights",
              "Tsunami",
              "Drought",
              "Blizzard",
              "Meteor shower",
            ],
          },
        ],
      },
      {
        heading: "Famous People (30 words)",
        wordGrids: [
          {
            label: "Easy (10)",
            words: [
              "Albert Einstein",
              "Cleopatra",
              "Shakespeare",
              "Mozart",
              "Beethoven",
              "Leonardo da Vinci",
              "Martin Luther King Jr.",
              "Abraham Lincoln",
              "Queen Elizabeth",
              "Santa Claus",
            ],
          },
          {
            label: "Medium (10)",
            words: [
              "Marie Curie",
              "Nelson Mandela",
              "Frida Kahlo",
              "Pablo Picasso",
              "Michael Jordan",
              "Serena Williams",
              "Taylor Swift",
              "Elvis Presley",
              "Marilyn Monroe",
              "Charlie Chaplin",
            ],
          },
          {
            label: "Hard (10)",
            words: [
              "Nikola Tesla",
              "Ada Lovelace",
              "Confucius",
              "Galileo",
              "Hypatia",
              "Rosa Parks",
              "Neil Armstrong",
              "Jane Goodall",
              "Stephen Hawking",
              "Amelia Earhart",
            ],
          },
        ],
      },
      {
        heading: "Phrases & Idioms (23 words)",
        wordGrids: [
          {
            label: "Easy (8)",
            words: [
              "Happy birthday",
              "Good morning",
              "Trick or treat",
              "Happy new year",
              "Break a leg",
              "Piece of cake",
              "Time flies",
              "Once upon a time",
            ],
          },
          {
            label: "Medium (8)",
            words: [
              "Under the weather",
              "Hit the books",
              "Spill the beans",
              "Cost an arm and a leg",
              "On cloud nine",
              "Bite the bullet",
              "Let the cat out of the bag",
              "When pigs fly",
            ],
          },
          {
            label: "Hard (7)",
            words: [
              "Burning the midnight oil",
              "The ball is in your court",
              "Beat around the bush",
              "A blessing in disguise",
              "Actions speak louder than words",
              "Every cloud has a silver lining",
              "Don't cry over spilled milk",
            ],
          },
        ],
      },
      {
        heading: "How to Build Your Own List",
        paragraphs: [
          "Mix categories so each round feels fresh. For a 20-minute party, draw 5 words each from animals, food, and movies, then finish with one hard phrase round.",
          "Our free online charades game includes 300+ curated words with automatic category and difficulty filters—no printing required.",
        ],
        list: [
          "Print this page or copy words onto slips for offline play.",
          "Use easy words only for kids under 8; add medium at ages 9–12.",
          "Pair with our rules page for props, gestures, and scoring basics.",
        ],
      },
    ],
    cta: "Try the Online Word Generator",
  },
  "charades-party-ideas": {
    meta: {
      title: "Charades Party Ideas - Themes, Rules & Group Game Tips",
      description:
        "Plan a memorable charades party with themed word lists, team formats, timers, and icebreaker ideas for friends, family, and office events.",
    },
    breadcrumb: "Charades Party Ideas",
    heading: "Charades Party Ideas for Any Group",
    intro:
      "Whether you are hosting a birthday, holiday gathering, or office icebreaker, charades is easy to set up and works for almost any group size.",
    sections: [
      {
        heading: "Party Formats That Work",
        list: [
          "Classic teams: two groups alternate actors and guessers.",
          "All-play: one actor, everyone guesses—fast and chaotic fun.",
          "Theme rounds: movies, holidays, or decade-specific words.",
          "Relay charades: short 30-second bursts per player.",
        ],
      },
      {
        heading: "Themed Charades Night Ideas",
        list: [
          "Hollywood night: movies, actors, and famous quotes.",
          "Holiday party: Christmas, Halloween, or New Year words.",
          "Travel theme: countries, landmarks, and foods.",
          "Office edition: job tasks, meeting moments (keep it kind!).",
        ],
      },
      {
        heading: "What You Need",
        list: [
          "A word generator or printed word list.",
          "Phone timer or our built-in online timer.",
          "Scorekeeper (optional).",
          "Open space so actors can move safely.",
        ],
      },
      {
        heading: "Make It More Fun",
        paragraphs: [
          "Add small prizes for best actor, funniest guess, or fastest round.",
          "Film-free rule keeps focus on performance and keeps the game fair.",
        ],
      },
    ],
    cta: "Start a Free Charades Party Game",
  },
  "charades-for-adults": {
    meta: {
      title: "Charades for Adults - Hard Words, Party Rules & Team Ideas",
      description:
        "Adult charades word lists, spicier party rules, and team formats for dinner parties, office events, and game nights with friends.",
    },
    breadcrumb: "Charades for Adults",
    heading: "Charades for Adults: Challenging Words & Party Formats",
    intro:
      "Adult charades raises the difficulty with abstract phrases, pop culture references, and fast-paced team play. Use these ideas for dinner parties, holiday gatherings, or office happy hours.",
    sections: [
      {
        heading: "What Makes Adult Charades Different",
        paragraphs: [
          "Longer phrases, idioms, and niche references make rounds more challenging and funnier.",
          "Teams often use shorter timers (45–60 seconds) and allow themed rounds like movies, brands, or decade trivia.",
        ],
      },
      {
        heading: "Hard Charades Words for Adults",
        list: [
          "Phrases: break the ice, once in a blue moon, caught red-handed",
          "Movies: Pulp Fiction, Parasite, The Prestige, Memento",
          "Jobs & life: job interview, tax season, group chat drama",
          "Pop culture: viral meme, streaming binge, coffee run",
        ],
      },
      {
        heading: "Party Formats Adults Enjoy",
        list: [
          "Reverse charades: the team acts while one person guesses.",
          "Villain round: only antagonists from films and books.",
          "No-hands round: facial expressions and body angles only.",
          "Speed bracket: elimination tournament between pairs.",
        ],
      },
      {
        heading: "Hosting Tips",
        list: [
          "Curate words ahead of time—avoid anything offensive or too obscure.",
          "Pair shy guests with confident actors for the first round.",
          "Keep alcohol-friendly rules clear: no speaking, no phone hints.",
          "Use our online timer and 300+ word library to run rounds smoothly.",
        ],
      },
    ],
    cta: "Play Adult Charades Online",
  },
  "charades-themes": {
    meta: {
      title: "Charades Themes - Movie, Holiday & Category Night Ideas",
      description:
        "Plan themed charades nights with curated word lists for movies, animals, holidays, decades, and TV shows. Easy setup for any group size.",
    },
    breadcrumb: "Charades Themes",
    heading: "Charades Themes for Memorable Game Nights",
    intro:
      "Themed rounds keep charades fresh. Pick one theme per night or rotate categories between rounds so every player gets words they enjoy.",
    sections: [
      {
        heading: "Popular Theme Ideas",
        list: [
          "Hollywood night: films, actors, famous quotes",
          "Animal kingdom: pets, wildlife, mythical creatures",
          "Sports mania: athletes, equipment, stadium moments",
          "Food tour: dishes, cooking actions, restaurant scenes",
          "Decade throwback: 80s, 90s, or 2000s pop culture",
        ],
      },
      {
        heading: "Holiday & Seasonal Themes",
        list: [
          "Halloween: monsters, costumes, trick-or-treat",
          "Thanksgiving: family dinner, parade, gratitude",
          "Summer BBQ: grill, beach, vacation",
          "New Year's Eve: countdown, fireworks, resolutions",
        ],
      },
      {
        heading: "How to Run a Theme Round",
        paragraphs: [
          "Announce the theme before each round so guessers know which category to expect.",
          "Mix easy and hard words within the theme so beginners and experts both stay engaged.",
          "Award bonus points for the best themed performance, not just the fastest guess.",
        ],
      },
      {
        heading: "Build a Theme Pack Fast",
        list: [
          "Filter by category in our free online charades game.",
          "Print or share a short list of 20–30 words per theme.",
          "Rotate themes every 15 minutes to keep energy high.",
        ],
      },
    ],
    cta: "Start a Themed Charades Game",
  },
  "christmas-charades": {
    meta: {
      title: "Christmas Charades - Holiday Words, Rules & Family Ideas",
      description:
        "Christmas charades word lists and family-friendly rules for holiday parties. Festive ideas for kids, adults, and mixed-age groups.",
    },
    breadcrumb: "Christmas Charades",
    heading: "Christmas Charades: Festive Words for Holiday Parties",
    intro:
      "Christmas charades is a perfect low-prep activity for family gatherings and office holiday parties. Use these festive words and simple rule tweaks for all ages.",
    sections: [
      {
        heading: "Christmas Charades Word Ideas",
        list: [
          "Santa Claus, reindeer, elf, snowman, gingerbread house",
          "Decorating the tree, wrapping gifts, caroling, baking cookies",
          "North Pole, sleigh, chimney, stockings, mistletoe",
          "Frosty the Snowman, Grinch, Nutcracker, Ebenezer Scrooge",
          "Hot cocoa, candy cane, eggnog, fruitcake, turkey dinner",
        ],
      },
      {
        heading: "Family-Friendly Rules",
        list: [
          "Use easy words for kids and harder holiday phrases for adults.",
          "Allow 90-second rounds when younger children act.",
          "Teams can be mixed ages—pair kids with adults.",
          "Skip scary or complex words if the group prefers lighthearted fun.",
        ],
      },
      {
        heading: "Holiday Party Formats",
        list: [
          "Stocking surprise: each team draws words from a festive hat.",
          "Ornament relay: fastest correct guess hangs an ornament on the tree.",
          "Carol charades: act a song title without humming lyrics.",
        ],
      },
      {
        heading: "Make It Extra Festive",
        paragraphs: [
          "Play in front of the tree, wear ugly sweaters, or add small prizes for best holiday acting.",
          "Combine with our free online charades game—filter easy words and use the built-in timer.",
        ],
      },
    ],
    cta: "Play Christmas Charades Online",
  },
  "halloween-charades": {
    meta: {
      title: "Halloween Charades - 60+ Words, Party Script & Rules",
      description:
        "60+ Halloween charades words for kids and adults, a 10-minute party script, classroom rules, and example rounds for October gatherings.",
    },
    breadcrumb: "Halloween Charades",
    heading: "Halloween Charades: 60+ Words & a 10-Minute Party Plan",
    intro:
      "Halloween charades is one of the easiest October party games: no printing, one phone for the timer, and words everyone already knows from costumes and movies. Below is a full word list by difficulty, a step-by-step party script for 8–12 guests, and rules for classrooms vs. home parties.",
    sections: [
      {
        heading: "10-Minute Halloween Party Script",
        paragraphs: [
          "Use this flow when guests arrive in costume and you want a fast icebreaker before candy or music. Adjust times for larger groups.",
        ],
        orderedList: [
          "0:00 — Split into two teams. Explain: no talking, no props, 60-second rounds.",
          "1:00 — Demo round with an adult acting “vampire” (category gesture + fangs + cape).",
          "3:00 — Round 1: Team A uses 5 words from the Easy Creatures list below.",
          "5:00 — Round 2: Team B uses 5 words from Actions & Places.",
          "7:00 — Optional “costume charades”: act only as your outfit character.",
          "9:00 — Final lightning round: any easy word, 30 seconds each.",
          "10:00 — Tally points or skip scoring and hand out candy for best performance.",
        ],
      },
      {
        heading: "Halloween Charades Word List (60+ Ideas)",
        paragraphs: [
          "Copy words onto slips, or use our free online charades game with easy/medium filters. Mix categories so each round feels different.",
        ],
        wordGrids: [
          {
            label: "Easy — Creatures & Characters (20)",
            words: [
              "Vampire",
              "Witch",
              "Ghost",
              "Zombie",
              "Mummy",
              "Werewolf",
              "Bat",
              "Spider",
              "Black cat",
              "Owl",
              "Skeleton",
              "Goblin",
              "Troll",
              "Wizard",
              "Frankenstein",
              "Pumpkin",
              "Jack-o-lantern",
              "Monster",
              "Grim reaper",
              "Creepy doll",
            ],
          },
          {
            label: "Easy — Actions & Places (15)",
            words: [
              "Trick or treat",
              "Carving pumpkins",
              "Bobbing for apples",
              "Haunted house",
              "Costume contest",
              "Decorating",
              "Knocking on door",
              "Running away",
              "Hiding",
              "Scaring someone",
              "Eating candy",
              "Dressing up",
              "Face paint",
              "Flashlight walk",
              "Trick or treating",
            ],
          },
          {
            label: "Medium — Movies & Shows (15)",
            words: [
              "Hocus Pocus",
              "Nightmare Before Christmas",
              "Harry Potter",
              "Casper",
              "Beetlejuice",
              "Ghostbusters",
              "Scooby-Doo",
              "Addams Family",
              "Coraline",
              "Hotel Transylvania",
              "Dracula",
              "The Witches",
              "Gremlins",
              "Coco",
              "It Follows",
            ],
          },
          {
            label: "Medium — Spooky Phrases (12)",
            words: [
              "Full moon",
              "Candy bucket",
              "Spider web",
              "Witch's brew",
              "Haunted mansion",
              "Black and orange",
              "Spooky forest",
              "Midnight hour",
              "Creaky door",
              "Howling wind",
              "Cauldron bubble",
              "Broomstick ride",
            ],
          },
        ],
      },
      {
        heading: "Classroom vs. Costume Party Rules",
        table: {
          headers: ["Situation", "Recommended rule"],
          rows: [
            ["Elementary classroom", "Easy lists only; 90-second rounds; allow one buddy helper"],
            ["Middle school", "Add medium movie titles; no horror gore words"],
            ["Family living room", "Mixed easy + medium; one skip per turn"],
            ["Teen costume party", "Costume charades round; 45-second fast rounds"],
            ["Preschool", "Pictures or adult whispers the word; no scoring"],
          ],
        },
      },
      {
        heading: "Example Round: Acting “Haunted House”",
        paragraphs: [
          "Actor holds up two fingers, then acts word one: wide eyes, tiptoe, hands up like something scary is nearby. After “haunted” is guessed, one finger for word two—draw a roof, open a door, step inside slowly. This two-beat structure works for most Halloween phrases.",
        ],
      },
      {
        heading: "Kid-Safe Tips for Teachers & Parents",
        list: [
          "Preview the medium movie list—drop titles your group finds too intense.",
          "Pair shy kids with a confident partner; both can act together.",
          "Use charades after vocabulary units: students act unit words only.",
          "Keep score optional; praise creative mime over speed.",
          "Link to our classroom charades article for a full 15-minute lesson plan.",
        ],
      },
      {
        heading: "Hosting & Atmosphere",
        paragraphs: [
          "Dim lights and Halloween décor set the mood, but keep the play area safe—clear floor space for big gestures.",
          "Use our free online charades game for instant words and a built-in timer. Filter easy difficulty for mixed ages, or copy words from the lists above into a bowl for classic slip drawing.",
        ],
      },
    ],
    cta: "Play Halloween Charades Online",
  },
  "team-building-charades": {
    meta: {
      title: "Team Building Charades - Office Icebreaker Ideas & Rules",
      description:
        "Run charades for team building and office icebreakers: formats, workplace-safe words, and tips for hybrid or in-person groups.",
    },
    breadcrumb: "Team Building Charades",
    heading: "Team Building Charades for Offices & Groups",
    intro:
      "Charades is one of the fastest icebreakers for new teams, retreats, and hybrid meetings. These formats keep play inclusive, professional, and fun.",
    sections: [
      {
        heading: "Why Charades Works for Team Building",
        list: [
          "Low prep—no materials beyond a word list and timer.",
          "Encourages non-verbal communication and collaboration.",
          "Breaks hierarchy: everyone performs and guesses.",
          "Fits 10–40 players in teams or all-play mode.",
        ],
      },
      {
        heading: "Workplace-Safe Word Ideas",
        list: [
          "Actions: brainstorming, presentation, coffee break, deadline",
          "Objects: laptop, whiteboard, sticky note, headset",
          "Soft humor: Monday morning, team lunch, Zoom call",
          "Avoid sensitive topics, politics, or inside jokes that exclude new hires.",
        ],
      },
      {
        heading: "Recommended Formats",
        list: [
          "Department vs department teams with 5-round cap.",
          "Reverse charades for large all-hands meetings.",
          "Theme round: company values acted as phrases.",
          "5-minute warm-up before longer workshops.",
        ],
      },
      {
        heading: "Facilitator Checklist",
        paragraphs: [
          "Explain rules clearly, emphasize respect and inclusivity.",
          "Use our online charades tool for instant words and timers in hybrid rooms.",
          "Debrief briefly: what made communication effective?",
        ],
      },
    ],
    cta: "Start a Team Charades Game",
  },
};

export default en;
